#!/bin/bash
## Generate nginx uploads proxy when remote-media credentials are configured.
## Credentials: copy env/remote-media.env.example to env/remote-media.env
##
## DDEV sources *.sh in web-entrypoint.d — never use exit in this file.

uploads_proxy_setup() {
    local ENV_FILE="/mnt/ddev_config/env/remote-media.env"
    # Writable inside the container (.ddev/nginx is read-only on the mount).
    local NGINX_CONF="/etc/nginx/snippets/ddev-uploads-proxy.conf"

    mkdir -p /etc/nginx/snippets

    if [[ -f "$ENV_FILE" ]]; then
        set -a
        # shellcheck source=/dev/null
        source "$ENV_FILE"
        set +a
    fi

    local host="${REMOTE_MEDIA_HOST:-eslov.se}"
    local scheme="${REMOTE_MEDIA_SCHEME:-https}"
    local auth_header=""

    if [[ -n "${REMOTE_MEDIA_USER:-}" && -n "${REMOTE_MEDIA_PASSWORD:-}" ]]; then
        local auth
        auth=$(printf '%s:%s' "$REMOTE_MEDIA_USER" "$REMOTE_MEDIA_PASSWORD" | base64 -w 0 2>/dev/null || printf '%s:%s' "$REMOTE_MEDIA_USER" "$REMOTE_MEDIA_PASSWORD" | base64 | tr -d '\n')
        auth_header="    proxy_set_header Authorization \"Basic ${auth}\";"
    fi

    cat >"$NGINX_CONF" <<EOF
# Generated by uploads-proxy.sh — do not edit (edit env/remote-media.env instead)
# LTS production uses /app/uploads/ (Bedrock). Legacy attachment guids may use /wp-content/uploads/.
location ^~ /app/uploads/ {
    proxy_pass ${scheme}://${host};
    proxy_ssl_server_name on;
    proxy_set_header Host ${host};
${auth_header}
}
location ^~ /wp-content/uploads/ {
    proxy_pass ${scheme}://${host}/app/uploads/;
    proxy_ssl_server_name on;
    proxy_set_header Host ${host};
${auth_header}
}
EOF
}

uploads_proxy_setup
